services:
  gateway-1:
    image: ghcr.io/cludus/gateway-nodejs:latest
    environment:
      NODE_ENV: "test"
      WS_PATH: "/websocket"
      METRICS_PATH: "/actuator/prometheus"
      METRICS_CONNECTIONS_COUNT_KEY: "cludus_gateway_connections_count"
      METRICS_MESSAGES_COUNT_KEY: "cludus_gateway_messages_count"
      METRICS_MESSAGES_TIMER_KEY: "cludus_gateway_messages_latency"
    ports:
      - "8080:8080"
    profiles:
      - test

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - gateway-1
    profiles:
      - test

  prometheus-dev:
    image: prom/prometheus:latest
    extra_hosts:
      - "gateway-dev:127.0.0.1"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
    profiles:
      - dev

  loki-dev:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    profiles:
      - dev

  grafana-dev:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    profiles:
      - dev
