services:
  gateway-1:
    image: ghcr.io/cludus/gateway-nodejs:latest
    environment:
      NODE_ENV: "test"
      WS_PATH: "/websocket"
      PROMETHEUS_PATH: "/actuator/prometheus"
      PROMETHEUS_METRICS_CONNECTIONS_COUNT_KEY: "cludus_gateway_connections_count"
      PROMETHEUS_METRICS_MESSAGES_COUNT_KEY: "cludus_gateway_messages_count"
      PROMETHEUS_METRICS_MESSAGES_TIMER_KEY: "cludus_gateway_messages_latency"
    ports:
      - "8080:8080"
    profiles:
      - test

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - gateway-1
    profiles:
      - test

  prometheus-dev:
    image: prom/prometheus:latest
    extra_hosts:
      - "gateway-dev:127.0.0.1"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
    profiles:
      - dev
