global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "cludus-gateway-metrics"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-1:8080"]
        labels:
          application: "cludus-gateway"
