name: build
run-name: ${{ github.actor }} is building 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: install-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
