name: release
run-name: ${{ github.actor }} is releasing 🚀
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
      # build to node
      # publish to github packages
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build -t ghcr.io/cludus/gateway-nodejs:latest .
          docker push ghcr.io/cludus/gateway-nodejs:latest
          docker build -t ghcr.io/cludus/gateway-nodejs:${{ github.ref_name }} .
          docker push ghcr.io/cludus/gateway-nodejs:${{ github.ref_name }}
