name: Release New Version
run-name: ${{ github.actor }} is releasing 🚀
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '>=20.0.0'
    - name: Build
      run: |
        npm ci
        CI=true npm run build
    - name: Github Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Version ${{ github.ref_name }}
        draft: false
        prerelease: false

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build -t ghcr.io/cludus/gateway-nodejs:latest .
          docker push ghcr.io/cludus/gateway-nodejs:latest
          docker build -t ghcr.io/cludus/gateway-nodejs:${{ github.ref_name }} .
          docker push ghcr.io/cludus/gateway-nodejs:${{ github.ref_name }}
