name: release
run-name: ${{ github.actor }} is releasing 🚀
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: write
  packages: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build -t ghcr.io/cludus/gateway-nodejs:latest .
          docker push ghcr.io/cludus/gateway-nodejs:latest
